// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/envoy-proxy-bouncer/bouncer (interfaces: CaptchaService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_captcha_service.go -package=mocks github.com/kdwils/envoy-proxy-bouncer/bouncer CaptchaService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	components "github.com/kdwils/envoy-proxy-bouncer/bouncer/components"
	gomock "go.uber.org/mock/gomock"
)

// MockCaptchaService is a mock of CaptchaService interface.
type MockCaptchaService struct {
	ctrl     *gomock.Controller
	recorder *MockCaptchaServiceMockRecorder
	isgomock struct{}
}

// MockCaptchaServiceMockRecorder is the mock recorder for MockCaptchaService.
type MockCaptchaServiceMockRecorder struct {
	mock *MockCaptchaService
}

// NewMockCaptchaService creates a new mock instance.
func NewMockCaptchaService(ctrl *gomock.Controller) *MockCaptchaService {
	mock := &MockCaptchaService{ctrl: ctrl}
	mock.recorder = &MockCaptchaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptchaService) EXPECT() *MockCaptchaServiceMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockCaptchaService) DeleteSession(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSession", sessionID)
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockCaptchaServiceMockRecorder) DeleteSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockCaptchaService)(nil).DeleteSession), sessionID)
}

// GenerateChallengeURL mocks base method.
func (m *MockCaptchaService) GenerateChallengeURL(ip, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChallengeURL", ip, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChallengeURL indicates an expected call of GenerateChallengeURL.
func (mr *MockCaptchaServiceMockRecorder) GenerateChallengeURL(ip, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChallengeURL", reflect.TypeOf((*MockCaptchaService)(nil).GenerateChallengeURL), ip, originalURL)
}

// GetProviderName mocks base method.
func (m *MockCaptchaService) GetProviderName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProviderName indicates an expected call of GetProviderName.
func (mr *MockCaptchaServiceMockRecorder) GetProviderName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderName", reflect.TypeOf((*MockCaptchaService)(nil).GetProviderName))
}

// GetSession mocks base method.
func (m *MockCaptchaService) GetSession(sessionID string) (*components.CaptchaSession, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*components.CaptchaSession)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockCaptchaServiceMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockCaptchaService)(nil).GetSession), sessionID)
}

// IsEnabled mocks base method.
func (m *MockCaptchaService) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockCaptchaServiceMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockCaptchaService)(nil).IsEnabled))
}

// RenderChallenge mocks base method.
func (m *MockCaptchaService) RenderChallenge(siteKey, callbackURL, redirectURL, sessionID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderChallenge", siteKey, callbackURL, redirectURL, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderChallenge indicates an expected call of RenderChallenge.
func (mr *MockCaptchaServiceMockRecorder) RenderChallenge(siteKey, callbackURL, redirectURL, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderChallenge", reflect.TypeOf((*MockCaptchaService)(nil).RenderChallenge), siteKey, callbackURL, redirectURL, sessionID)
}

// StartCleanup mocks base method.
func (m *MockCaptchaService) StartCleanup(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCleanup", ctx)
}

// StartCleanup indicates an expected call of StartCleanup.
func (mr *MockCaptchaServiceMockRecorder) StartCleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCleanup", reflect.TypeOf((*MockCaptchaService)(nil).StartCleanup), ctx)
}

// VerifyResponse mocks base method.
func (m *MockCaptchaService) VerifyResponse(ctx context.Context, req components.VerificationRequest) (*components.VerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyResponse", ctx, req)
	ret0, _ := ret[0].(*components.VerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyResponse indicates an expected call of VerifyResponse.
func (mr *MockCaptchaServiceMockRecorder) VerifyResponse(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyResponse", reflect.TypeOf((*MockCaptchaService)(nil).VerifyResponse), ctx, req)
}
