// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/envoy-proxy-bouncer/server (interfaces: Remediator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_remediator.go -package=mocks github.com/kdwils/envoy-proxy-bouncer/server Remediator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	authv3 "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"
	remediation "github.com/kdwils/envoy-proxy-bouncer/remediation"
	gomock "go.uber.org/mock/gomock"
)

// MockRemediator is a mock of Remediator interface.
type MockRemediator struct {
	ctrl     *gomock.Controller
	recorder *MockRemediatorMockRecorder
	isgomock struct{}
}

// MockRemediatorMockRecorder is the mock recorder for MockRemediator.
type MockRemediatorMockRecorder struct {
	mock *MockRemediator
}

// NewMockRemediator creates a new mock instance.
func NewMockRemediator(ctrl *gomock.Controller) *MockRemediator {
	mock := &MockRemediator{ctrl: ctrl}
	mock.recorder = &MockRemediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemediator) EXPECT() *MockRemediatorMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockRemediator) Check(ctx context.Context, req *authv3.CheckRequest) remediation.CheckedRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, req)
	ret0, _ := ret[0].(remediation.CheckedRequest)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockRemediatorMockRecorder) Check(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockRemediator)(nil).Check), ctx, req)
}

// Metrics mocks base method.
func (m *MockRemediator) Metrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Metrics indicates an expected call of Metrics.
func (mr *MockRemediatorMockRecorder) Metrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metrics", reflect.TypeOf((*MockRemediator)(nil).Metrics), ctx)
}

// Sync mocks base method.
func (m *MockRemediator) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockRemediatorMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockRemediator)(nil).Sync), ctx)
}
