// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/envoy-proxy-bouncer/remediation (interfaces: Bouncer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_bouncer.go -package=mocks github.com/kdwils/envoy-proxy-bouncer/remediation Bouncer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBouncer is a mock of Bouncer interface.
type MockBouncer struct {
	ctrl     *gomock.Controller
	recorder *MockBouncerMockRecorder
	isgomock struct{}
}

// MockBouncerMockRecorder is the mock recorder for MockBouncer.
type MockBouncerMockRecorder struct {
	mock *MockBouncer
}

// NewMockBouncer creates a new mock instance.
func NewMockBouncer(ctrl *gomock.Controller) *MockBouncer {
	mock := &MockBouncer{ctrl: ctrl}
	mock.recorder = &MockBouncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBouncer) EXPECT() *MockBouncerMockRecorder {
	return m.recorder
}

// Bounce mocks base method.
func (m *MockBouncer) Bounce(ctx context.Context, ip string, headers map[string]string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bounce", ctx, ip, headers)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bounce indicates an expected call of Bounce.
func (mr *MockBouncerMockRecorder) Bounce(ctx, ip, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bounce", reflect.TypeOf((*MockBouncer)(nil).Bounce), ctx, ip, headers)
}

// Metrics mocks base method.
func (m *MockBouncer) Metrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Metrics indicates an expected call of Metrics.
func (mr *MockBouncerMockRecorder) Metrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metrics", reflect.TypeOf((*MockBouncer)(nil).Metrics), ctx)
}

// Sync mocks base method.
func (m *MockBouncer) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockBouncerMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockBouncer)(nil).Sync), ctx)
}
