name: charts

on:
  push:
    branches:
      - 'charts/**'

permissions:
  contents: write
  packages: write

jobs:
  charts:
    uses: ./.github/workflows/helm-publish.yaml
    with:
      charts_dir: charts/envoy-proxy-bouncer
      oci_registry: ghcr.io
