name: releaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write
concurrency:
  group: goreleaser
  cancel-in-progress: true

jobs:
  tag:
    uses: kdwils/homelab-workflow/.github/workflows/update-image-tag.yml@main
    secrets: inherit
    with:
      image: ${{ github.repository_owner }}/envoy-proxy-bouncer
      registry: ghcr.io

  charts:
    needs: [tag]
    uses: kdwils/homelab-workflow/.github/workflows/helm-publish-oci.yml@main
    with:
      charts_dir: charts/envoy-proxy-bouncer

  goreleaser:
    needs: [tag]
    if: "!contains(github.ref, '-rc')"
    uses: kdwils/homelab-workflow/.github/workflows/go-releaser.yml@main
    secrets: inherit
